



using UnityEngine;
using System.Collections;
using PixelCrushers.DialogueSystem;
using PixelCrushers.DialogueSystem.SequencerCommands;

public class SequencerCommandSendConversation : SequencerCommand {


	string senderName,receiverName,messageName;


	public void Start() {



		// Add your initialization code here. You can use the GetParameter***() and GetSubject()
		// functions to get information from the command's parameters. You can also use the
		// Sequencer property to access the SequencerCamera, CameraAngle, and other properties
		// on the sequencer.

		messageName = GetParameter(2);
		senderName = GetParameter(0);
		receiverName = GetParameter(1);

		switch(senderName)
		{
		case "SM":
			senderName = "Sales Manager";
			break;
		case "LO":
			senderName = "LPU Officer";
			break;
		case "LM":
			senderName = "LPU Manager";
			break;
		case "CR":
			senderName = "Credit Risk";
			break;
		default:
			break;


		}

		switch(receiverName)
		{
		case "SM":
			receiverName = "Sales Manager";
			break;
		case "LO":
			receiverName = "LPU Officer";
			break;
		case "LM":
			receiverName = "LPU Manager";
			break;
		case "CR":
			receiverName = "Credit Risk";
			break;
		default:
			break;
			
			
		}

	


		GameObject.Find ("Dialogue Manager").GetComponent<NPCsync>().sendMessageRPC(senderName,receiverName,messageName);
	}
	
	public void Update() {


		//set lock to false so others can interact with this object
		//transform.GetComponent<DetectObjects>().photonView.RPC("setInteractLock",PhotonTargets.AllBuffered, false);
		
		//delete the useless script generated by dunilog

		


//		if( GameObject.Find("InventoryObj").GetComponent<inventory>().inventoryObject == null)
//		{
//			PhotonView photonView = onUsedObj.GetPhotonView();
//			
//			photonView.RPC("disableRenderer",PhotonTargets.AllBuffered);
//			photonView.RPC("disableCollider",PhotonTargets.AllBuffered);
//			photonView.RPC("disableRigidbody",PhotonTargets.AllBuffered);
//			
//			
//			moveToPlayerPosition(onUsedObj.name);
//			disableRender(onUsedObj.name);
//			disableCollider(onUsedObj.name);
//			disableRigidbody(onUsedObj.name);
//			enableInventory(onUsedObj);
//		}
//		Stop ();
		// Add your update code here. When the command is done, call Stop().

	}



	
	public void OnDestroy() {
		// Add your finalization code here. This is critical. If the sequence is cancelled and this
		// command is marked as "required", then only Start() and OnDestroy() will be called.

	}






	
}
 
 

/**/