using UnityEngine;
using System.Collections;
using HutongGames.PlayMaker;

public class DialogEnd : MonoBehaviour {

	private PlayMakerFSM getState; //get variable from FSM

	void Start(){
		//Debug.Log("Here is: " + transform.parent);
		transform.GetComponent<DUGView>().visible = false;

		string hitColliderName = transform.GetComponent<DialogueController>().activeDialogue;

		//trying to get gameObj FSM -- added by Kris
		getState = GameObject.Find(hitColliderName).GetComponent<PlayMakerFSM>();
		if(getState != null)
		if (getState.FsmVariables.GetFsmBool("stop_to_talk").Value == true)
		{
			getState.FsmVariables.GetFsmBool("stop_to_talk").Value = false;
			
		}


		transform.parent.GetComponent<DetectObjects>().moveCameraToPlayer();
		transform.parent.GetComponent<DetectObjects>().enableCameraAndMotor();
		transform.parent.GetComponent<DetectObjects>().enteredDialog = false;
		//set lock to false so others can interact with this object
		//GameObject.Find(hitColliderName).GetComponent<TriggerHandler>().photonView.RPC("setInteractLock",PhotonTargets.AllBuffered, false);

		//delete the useless script generated by dunilog
		GameObject.Destroy(this.gameObject.transform.GetComponent<DialogEnd>());
		//this.transform.parent.GetComponent<TriggerHandler>().moveCameraToPlayer();
		//this.transform.parent.GetComponent<TriggerHandler>().enableCameraAndMotor();
	}
}
