using UnityEngine;
using System.Collections;

public class DialogEndWithGrab: MonoBehaviour {
	
	void Start(){
		
		transform.GetComponent<DUGView>().visible = false;
		
		string hitColliderName = transform.GetComponent<DialogueController>().activeDialogue;
		
		



		transform.parent.GetComponent<DetectObjects>().moveCameraToPlayer();
		transform.parent.GetComponent<DetectObjects>().enableCameraAndMotor();
		transform.parent.GetComponent<DetectObjects>().enteredDialog = false;
		//set lock to false so others can interact with this object
		//transform.GetComponent<DetectObjects>().photonView.RPC("setInteractLock",PhotonTargets.AllBuffered, false);
		
		//delete the useless script generated by dunilog
		GameObject targetObj = findGrabObjWithTag(GameObject.Find(hitColliderName).transform);

		if(targetObj != null && GameObject.Find("Inventory").GetComponent<inventory>().inventoryObject == null)
		{
			PhotonView photonView = targetObj.GetPhotonView();

			photonView.RPC("disableRenderer",PhotonTargets.AllBuffered);
			photonView.RPC("disableCollider",PhotonTargets.AllBuffered);
			photonView.RPC("disableRigidbody",PhotonTargets.AllBuffered);


			moveToPlayerPosition(targetObj.name);
			disableRender(targetObj.name);
			disableCollider(targetObj.name);
			disableRigidbody(targetObj.name);
			enableInventory(targetObj);
		}


		GameObject.Destroy(this.gameObject.transform.GetComponent<DialogEndWithGrab>());
		//this.transform.parent.GetComponent<TriggerHandler>().moveCameraToPlayer();
		//this.transform.parent.GetComponent<TriggerHandler>().enableCameraAndMotor();
	}


	void moveToPlayerPosition(string objName){

		GameObject obj  = GameObject.Find (objName);

		GameObject.Find ("Inventory").GetComponent<inventory>().inventoryObjectOriginalScale = obj.transform.lossyScale;

		obj.transform.position = this.transform.position;
		obj.transform.parent = this.transform.parent;

	}

	GameObject findGrabObjWithTag( Transform parent){

		if (parent.tag == "pickable")
			return parent.gameObject;
		else foreach (Transform child in parent){
			if(child.gameObject.tag == "pickable"){
				print (child.gameObject.name);
				return child.gameObject;
			}
		}

		return null;

	}



	void disableCollider(string objName){

		GameObject obj  = GameObject.Find (objName);
		Collider[] colliders = obj.GetComponentsInChildren<Collider>();
		
		foreach ( Collider c in colliders)
		{
			if(c.enabled == true)
				c.enabled = false;
		}

	}


	void disableRender(string objName)
	{

		GameObject obj  = GameObject.Find (objName);
		Renderer[] renderers = obj.GetComponentsInChildren<Renderer>();

		foreach ( Renderer r in renderers)
		{
			if(r.enabled == true)
				r.enabled = false;
		}
	}


	void disableRigidbody(string objName)
	{

		GameObject obj  = GameObject.Find (objName);
		if (obj.GetComponent<Rigidbody>()!=null)
			Destroy(obj.GetComponent<Rigidbody>());
	}
	void enableInventory(GameObject obj){

		GameObject.Find ("Inventory").GetComponent<GUITexture>().enabled = true;
		GameObject.Find ("Inventory").GetComponent<inventory>().updateInventoryObject(obj);

	}
}
